#!/usr/bin/perl

# Change these to suit your needs.
my $DB_NAME = "food";
my $DB_SERVER = "localhost";
my $DB_USER = "food";
my $DB_PWD = "food";


use strict;
use JSON;

my $pwd = `pwd`; chomp $pwd;
my $file = "$pwd/db_description.json";
my $json = do { local $/ = undef; open my $fh, "<", $file or die "Could not open $file: $!"; <$fh>; };
my $data = decode_json($json);
my $field_separator = $data->{"field_separator"};
my $text_separator = $data->{"text_separator"};
my $header = "USDA National Nutrient Database for Standard Reference, Release " . $data->{"version"} . " (" . $data->{"url"} . ")";
my $header_length = length($header);


# Output header.
print sql_comment("="x$header_length). "\n";
print sql_comment($header) . "\n";
print sql_comment("This file was generated by http://github/m5n/usda-nutrient-database-sql-port") . "\n";
print sql_comment("Run this SQL with an account that has admin priviledges, e.g.: mysql -v -u root < file.sql") . "\n";
print sql_comment("="x$header_length). "\n\n";


# Set up database.
print sql_drop_database($DB_NAME) . "\n";
print sql_create_database($DB_NAME) . "\n";
print sql_use_database($DB_NAME) . "\n\n";


# Set up user.
print sql_drop_user($DB_USER, $DB_SERVER) . "\n";
print sql_create_user($DB_USER, $DB_PWD, $DB_NAME, $DB_SERVER) . "\n\n";


# Set up tables.
# All tables must be defined before we can add foreign keys.
# All data must be loaded before we can add foreign keys, otherwise we must guarantee to load foreign keyed tables before other tables.
# So start with tables and primary keys, then load data into the tables, and lastly add the foreign keys.
foreach (@{$data->{"tables"}}) {
    my %table = %{$_};
    my $table_name = substr($table{"file"}, 0, -length(".txt"));
    my $saw_one = 0;
    my @primary_keys = ();

    print sql_comment("File " . $table{"file"} . ": " . $table{"description"}) . "\n";
    print sql_create_table_start($table_name) . "\n";
    foreach (@{$table{"fields"}}) {
        print ",\n\n" if $saw_one;
        $saw_one = 1;

        my %field = %{$_};
        my $datatype = sql_datatype_def($field{"type"}, $field{"size"}, 1);
        print "    " . sql_comment($field{"description"}) . "\n";
        print "    " . sql_field_def($field{"name"}, $datatype, $field{"blank"});

        push @primary_keys, $field{"name"} if $field{"is_primary_key"};
    }
    print "\n";
    print sql_create_table_end() . "\n";

    print sql_add_primary_keys($table_name, @primary_keys) . "\n" if $#primary_keys >= 0;

    print "\n";
}

# Then add data.
foreach (@{$data->{"tables"}}) {
    my %table = %{$_};
    my $table_name = substr($table{"file"}, 0, -length(".txt"));

    print sql_load_file("$pwd/data/" . $table{"file"}, $table_name, $field_separator, $text_separator) . "\n";

    # Assert all records were loaded.  Make sure a SQL error is generated if the count is off.
    print sql_assert_record_count($table_name, $table{"records"}) . "\n\n";
}

# Correct data issues before adding foreign keys; see MODIFICATIONS file.
print sql_insert("DERIV_CD", ("Deriv_Cd" => "", "Deriv_Desc" => "Added by http://github/m5n/usda-nutrient-database-sql-port to avoid foreign key error on NUT_DATA")) . "\n";
print sql_insert("FOOD_DES", ("NDB_No" => "", "FdGrp_Cd" => "0100", "Long_Desc" => "Added by http://github/m5n/usda-nutrient-database-sql-port to avoid foreign key error on NUT_DATA", "Shrt_Desc" => "See Long_Desc")) . "\n";
print sql_insert("NUTR_DEF", ("Nutr_No" => "", "Units" => "g", "NutrDesc" => "Added by http://github/m5n/usda-nutrient-database-sql-port to avoid foreign key error on FOOTNOTE", "Num_Dec" => "0", "Sr_Order" => 0)) . "\n\n";

# Then add foreign keys.
foreach (@{$data->{"tables"}}) {
    my %table = %{$_};
    my $table_name = substr($table{"file"}, 0, -length(".txt"));


    foreach (@{$table{"fields"}}) {
        my %field = %{$_};

        print sql_add_foreign_key($table_name, $field{"name"}, $field{"foreign_key"}) . "\n" if $field{"foreign_key"};
    }
}

